// Export utility functions

/**
 * Export diagram as PNG
 * @param {SVGElement} svgElement - The SVG element to export
 * @param {string} filename - The filename for the export
 * @returns {Promise<void>}
 */
export async function exportAsPNG(svgElement, filename = 'diagram.png') {
  return new Promise((resolve, reject) => {
    try {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');

      // Get SVG dimensions
      const bbox = svgElement.getBBox();
      const width = bbox.width || svgElement.width.baseVal.value || 800;
      const height = bbox.height || svgElement.height.baseVal.value || 600;

      // Set canvas size with scale for better quality
      const scale = 2; // Higher resolution
      canvas.width = width * scale;
      canvas.height = height * scale;

      // Serialize SVG
      const svgData = new XMLSerializer().serializeToString(svgElement);
      const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
      const url = URL.createObjectURL(svgBlob);

      const img = new Image();

      img.onload = () => {
        // Fill white background
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        // Draw image scaled
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

        // Convert to blob and download
        canvas.toBlob((blob) => {
          downloadBlob(blob, filename);
          URL.revokeObjectURL(url);
          resolve();
        }, 'image/png');
      };

      img.onerror = (error) => {
        URL.revokeObjectURL(url);
        reject(new Error('Failed to load SVG image'));
      };

      img.src = url;
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Export diagram as SVG
 * @param {SVGElement} svgElement - The SVG element to export
 * @param {string} filename - The filename for the export
 */
export function exportAsSVG(svgElement, filename = 'diagram.svg') {
  const svgData = new XMLSerializer().serializeToString(svgElement);

  // Add XML declaration and make it standalone
  const svgBlob = new Blob(
    ['<?xml version="1.0" encoding="UTF-8"?>\n' + svgData],
    { type: 'image/svg+xml;charset=utf-8' }
  );

  downloadBlob(svgBlob, filename);
}

/**
 * Export diagram as PDF (using jsPDF)
 * Note: Requires jsPDF library to be loaded
 * @param {SVGElement} svgElement - The SVG element to export
 * @param {string} filename - The filename for the export
 */
export async function exportAsPDF(svgElement, filename = 'diagram.pdf') {
  // This is a placeholder. In a real implementation, you would:
  // 1. Load jsPDF library dynamically
  // 2. Convert SVG to canvas
  // 3. Add canvas to PDF
  // 4. Download PDF

  console.warn('PDF export requires jsPDF library');

  // For now, convert to PNG and let user save as PDF manually
  return exportAsPNG(svgElement, filename.replace('.pdf', '.png'));
}

/**
 * Export diagram code as text file
 * @param {string} code - The diagram code
 * @param {string} filename - The filename for the export
 */
export function exportAsText(code, filename = 'diagram.mmd') {
  const blob = new Blob([code], { type: 'text/plain;charset=utf-8' });
  downloadBlob(blob, filename);
}

/**
 * Export diagram code as Markdown
 * @param {string} code - The diagram code
 * @param {string} title - The diagram title
 * @param {string} filename - The filename for the export
 */
export function exportAsMarkdown(code, title = 'Mermaid Diagram', filename = 'diagram.md') {
  const markdown = `# ${title}

\`\`\`mermaid
${code}
\`\`\`

---
*Generated by Mermaid Diagram Editor*
`;

  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  downloadBlob(blob, filename);
}

/**
 * Export diagram as HTML
 * @param {string} code - The diagram code
 * @param {string} title - The diagram title
 * @param {string} filename - The filename for the export
 */
export function exportAsHTML(code, title = 'Mermaid Diagram', filename = 'diagram.html') {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true });
  </script>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #f9fafb;
    }
    h1 {
      color: #111827;
      margin-bottom: 20px;
    }
    .diagram-container {
      background: white;
      padding: 40px;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      display: flex;
      justify-content: center;
      align-items: center;
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="diagram-container">
    <pre class="mermaid">
${escapeHtml(code)}
    </pre>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  downloadBlob(blob, filename);
}

/**
 * Copy diagram code to clipboard
 * @param {string} code - The diagram code
 * @returns {Promise<boolean>} True if copied successfully
 */
export async function copyToClipboard(code) {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(code);
      return true;
    } else {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = code;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      const success = document.execCommand('copy');
      document.body.removeChild(textarea);
      return success;
    }
  } catch (error) {
    console.error('Copy to clipboard failed:', error);
    return false;
  }
}

/**
 * Copy SVG to clipboard
 * @param {SVGElement} svgElement - The SVG element to copy
 * @returns {Promise<boolean>} True if copied successfully
 */
export async function copySVGToClipboard(svgElement) {
  try {
    const svgData = new XMLSerializer().serializeToString(svgElement);

    if (navigator.clipboard && navigator.clipboard.write) {
      const blob = new Blob([svgData], { type: 'image/svg+xml' });
      const item = new ClipboardItem({ 'image/svg+xml': blob });
      await navigator.clipboard.write([item]);
      return true;
    } else {
      // Fallback: copy as text
      return await copyToClipboard(svgData);
    }
  } catch (error) {
    console.error('Copy SVG to clipboard failed:', error);
    return false;
  }
}

/**
 * Share diagram (using Web Share API if available)
 * @param {string} code - The diagram code
 * @param {string} title - The diagram title
 * @returns {Promise<boolean>} True if shared successfully
 */
export async function shareDiagram(code, title = 'Mermaid Diagram') {
  if (!navigator.share) {
    console.warn('Web Share API not supported');
    return false;
  }

  try {
    await navigator.share({
      title: title,
      text: code,
      // Note: files can also be shared if needed
    });
    return true;
  } catch (error) {
    // User cancelled or error occurred
    console.error('Share failed:', error);
    return false;
  }
}

/**
 * Generate shareable URL (for Mermaid Live Editor)
 * @param {string} code - The diagram code
 * @returns {string} URL to Mermaid Live Editor
 */
export function generateShareableURL(code) {
  const encoded = btoa(encodeURIComponent(code));
  return `https://mermaid.live/edit#${encoded}`;
}

// Helper functions

/**
 * Download a blob as a file
 * @param {Blob} blob - The blob to download
 * @param {string} filename - The filename
 */
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  // Clean up
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

/**
 * Escape HTML special characters
 * @param {string} text - Text to escape
 * @returns {string} Escaped text
 */
function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
